# Generated by Django 5.2.4 on 2025-07-07 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seance',
            name='coach',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='seances_coach', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together={('date', 'heure_debut', 'coach')},
        ),
    ]
