# Generated by Django 5.2.4 on 2025-07-09 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0002_alter_seance_unique_together_seance_coach_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RdvHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('objet', models.CharField(max_length=255)),
                ('code_rdv', models.IntegerField(choices=[(1, 'Présent'), (2, 'Absent'), (3, 'Annulé par le client'), (4, 'Annulé par le coach')])),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_historiques', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_historiques_coach', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-heure_debut'],
            },
        ),
    ]
