# Generated by Django 5.2.4 on 2025-07-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0003_rdvhistorique'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='code_rdv',
            field=models.IntegerField(choices=[(0, 'Non traité'), (1, 'Présent'), (2, 'Absent'), (3, 'Annulé par le client'), (4, 'Annulé par le coach')], default=0),
        ),
        migrations.AddField(
            model_name='seance',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RdvHistorique',
        ),
    ]
